name: CI
on: [push, pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1.6.0
                
      - name: Compile
        run: npm run compile

      - name: Run tests
        run: npm t
